#! /bin/sh
dedisperse test1702231.fil -B 8 -d 39999999994 > test1702231.tim

dedisperse test1702231.fil -B 8 -d 0 > test1702231_dm0.tim
reader test1702231_dm0.tim > test1702231_dm0.ascii

gnuplot -persist -e "plot 'test1702231_dm0.ascii' with lines"
/home/vishal/SIGPROC/sigproc/src/fold test1702231.tim -p 5000 -n 64 -o test1702231.sgl
reader test1702231.tim > test1702231.ascii
gnuplot -persist -e "plot 'test1702231.ascii' with lines"
gnuplot -persist -e "plot 'test1702231.sgl' with lines"
